### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by NovaliX-Dev** [frozenlib/include-doc#1]
Hey, i've found your projet and it got my attention.
So i tried to use it, but unfortunately it seems to not work.

Here is the command i used on the root of my projet (a typical rust project):
```
rustdoc-include --root ./
```

Here the code where i tried to include it :
```rust
// #![include_doc("README.md", start)]
// #![include_doc("README.md", end)]

#![warn(missing_docs)]

use proc_macro::TokenStream;
use proc_macro2::{Span as Span2, TokenStream as TokenStream2};
use syn::DeriveInput;

// the macros a here so that the other files can have access to them
// (i know that's kinda weird)
macro_rules! error {
    ($span: expr, $message: literal $(,$format_args: expr)*) => {
        syn::Error::new($span, format!($message $(,$format_args)*))
    };

    ($error_vec: ident, $span: expr, $message: literal $(,$format_args: expr)*) => {{
        let tokens = syn::Error::new($span, format!($message $(,$format_args)*))
            .into_compile_error();

        $error_vec.push(tokens);
    }};
}

macro_rules! handle_error {
    ($expr: expr, $error_vec: ident) => {
        match $expr {
            Ok(val) => Some(val),
            Err(err) => {
                $error_vec.push(err.into_compile_error());

                None
            }
        }
    };
}

mod attrs;
mod default;
mod derive;
mod top_attribute;
mod traits;

const DEFAULT_IDENT: &str = "default";

// #![include_doc("README.md", start)]
// #![include_doc("README.md", end)]
#[proc_macro_derive(BetterDefault, attributes(default))]
pub fn better_default(input: TokenStream) -> TokenStream {
    let input = syn::parse_macro_input!(input as DeriveInput);

    derive::derive(input).into()
}
```

I hope i'm not doing something wrong.

**Comment by frozenlib** [comment]
How about using `"../README.md"` instead of `"README.md"`?

Since the path to the markdown file needs to be specified as a relative path from the `.rs` file, with a standard directory structure, the path to the README from `lib.rs` is often `"../README.md"` rather than `"README.md"`.

Additionally, since `// #![include_doc]` expands to `//!` and `// #[include_doc]` (without `!`) expands to `///`, it might be better to use `// #[include_doc]` instead of `// #![include_doc]` in the `better_default` comment.

**Comment by NovaliX-Dev** [comment]
Thank you for your quick response.

I've tried your suggestions, and still nothing.

In the mean time i've tried to debug your program while it was running on my project, and it seems that [Attr::find_iter(input)](https://github.com/frozenlib/rustdoc-include/blob/6ae470f88e395b514ee6d7bf2fee77f45212bb27/src/main.rs#L173) in the `apply` function finds nothing in lib.rs, the file i've shared with you.

All of this makes me think there is a problem with the regex, but i can be wrong.

**Comment by frozenlib** [comment]
I copied and pasted your example into `lib.rs` created by `cargo init --lib`, and it worked correctly, so the issue might be related to the line endings.

The regular expression in `Attr::find_iter` is based on the assumption that the line endings are LF, and if the line endings are CR or CRLF, the result might be empty.

Similarly, markdown files are also based on the assumption of LF line endings, so using different line endings might cause issues.

If line endings other than LF are commonly used in `.rs` and `.md` files, I am considering implementing support for line endings other than LF.

**Comment by NovaliX-Dev** [comment]
> I copied and pasted your example into lib.rs created by cargo init --lib, and it worked correctly, so the issue might be related to the line endings.

You're right, my line ending was CRLF, not LF. Changing it to LF solved the issue.

I think implementing support for CRLF is a great idea.

Anyway, Thank you for your help !
